# Generated by Django 6.0.5 on 2026-05-21 19:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('populaire', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quartier',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ville',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_logement', models.CharField(choices=[('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('VILLA', 'Villa'), ('MAISON', 'Maison'), ('CHAMBRE', 'Chambre'), ('DUPLEX', 'Duplex'), ('BUREAU', 'Bureau'), ('TERRAIN', 'Terrain')], max_length=20)),
                ('type_offre', models.CharField(choices=[('LOCATION', 'À louer'), ('VENTE', 'À vendre'), ('COLOCATION', 'Colocation'), ('COURTE_DUREE', 'Courte durée')], default='LOCATION', max_length=20)),
                ('standing', models.CharField(choices=[('ECONOMIQUE', 'Économique'), ('STANDARD', 'Standard'), ('CONFORT', 'Confort'), ('LUXE', 'Luxe')], default='STANDARD', max_length=20)),
                ('meuble', models.CharField(choices=[('NON_MEUBLE', 'Non meublé'), ('SEMI_MEUBLE', 'Semi-meublé'), ('MEUBLE', 'Meublé')], default='NON_MEUBLE', max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('surface', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_chambres', models.PositiveIntegerField(default=1)),
                ('nb_salles_bain', models.PositiveIntegerField(default=1)),
                ('nb_toilettes', models.PositiveIntegerField(default=1)),
                ('etage', models.SmallIntegerField(default=0)),
                ('prix', models.PositiveBigIntegerField()),
                ('prix_negociable', models.BooleanField(default=False)),
                ('charges', models.PositiveBigIntegerField(default=0)),
                ('caution', models.PositiveBigIntegerField(default=0)),
                ('eau_courante', models.BooleanField(default=True)),
                ('electricite', models.BooleanField(default=True)),
                ('internet', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('gardien', models.BooleanField(default=False)),
                ('generateur', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('cuisine_equipee', models.BooleanField(default=False)),
                ('balcon', models.BooleanField(default=False)),
                ('securite', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('PUBLIE', 'Publié'), ('SUSPENDU', 'Suspendu'), ('ARCHIVE', 'Archivé'), ('LOUE', 'Loué / Vendu')], default='EN_ATTENTE', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('date_disponibilite', models.DateField(blank=True, null=True)),
                ('est_booste', models.BooleanField(default=False)),
                ('est_vedette', models.BooleanField(default=False)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('nb_favoris', models.PositiveIntegerField(default=0)),
                ('nb_contacts', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL)),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='logements.quartier')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='logements.ville')),
            ],
            options={
                'verbose_name': 'Logement',
                'ordering': ['-est_booste', '-est_vedette', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PhotoLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/%Y/%m/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='logements.logement')),
            ],
            options={
                'verbose_name': 'Photo',
                'ordering': ['ordre', 'cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_demande', models.CharField(choices=[('VISITE', 'Demande de visite'), ('RESERVATION', 'Réservation')], default='VISITE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('montant', models.PositiveBigIntegerField(default=0)),
                ('paye', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='logements.logement')),
            ],
            options={
                'verbose_name': 'Réservation',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('FRAUDE', 'Fraude / Arnaque'), ('FAUX_PHOTOS', 'Photos fausses'), ('PRIX_ABUSIF', 'Prix abusif'), ('INEXISTANT', 'Logement inexistant'), ('INAPPROPRIE', 'Contenu inapproprié'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='logements.logement')),
            ],
            options={
                'verbose_name': 'Signalement',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='quartier',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='logements.ville'),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_set', to='logements.logement')),
            ],
            options={
                'verbose_name': 'Favori',
                'ordering': ['-cree_le'],
                'unique_together': {('utilisateur', 'logement')},
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('approuve', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='logements.logement')),
            ],
            options={
                'verbose_name': 'Avis',
                'ordering': ['-cree_le'],
                'unique_together': {('logement', 'auteur')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='quartier',
            unique_together={('ville', 'nom')},
        ),
    ]
