# Generated by Django 6.0.5 on 2026-05-29 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requete', models.CharField(max_length=500)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('type_logement', models.CharField(blank=True, max_length=20)),
                ('prix_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('prix_max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nb_resultats', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_recherches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche historique',
                'ordering': ['-cree_le'],
            },
        ),
    ]
