# Generated by Django 6.0.5 on 2026-05-22 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_paiement', models.CharField(choices=[('RESERVATION', 'Réservation logement'), ('ABONNEMENT', 'Abonnement premium'), ('BOOST', 'Boost annonce')], max_length=20)),
                ('methode', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('ESPECES', 'Espèces')], max_length=20)),
                ('montant', models.PositiveBigIntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='logements.reservation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('BASIC', 'Basic — Gratuit'), ('STARTER', 'Starter — 5 000 FCFA/mois'), ('PRO', 'Pro — 10 000 FCFA/mois'), ('BUSINESS', 'Business — 25 000 FCFA/mois')], default='BASIC', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'ordering': ['-cree_le'],
            },
        ),
    ]
