# Generated by Django 6.0.5 on 2026-06-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='code_confirmation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='message_operateur',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEMENT', 'En cours de traitement'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
