# Generated by Django 6.0.5 on 2026-06-18 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('MESSAGE', 'Nouveau message'), ('RESERVATION', 'Réservation'), ('VALIDATION', 'Annonce validée'), ('REJET', 'Annonce rejetée'), ('AVIS', 'Nouvel avis'), ('PAIEMENT', 'Paiement'), ('FAVORI', 'Nouveau favori'), ('SYSTEME', 'Système')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'lue'], name='notifs_noti_destina_b41a01_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-cree_le'], name='notifs_noti_cree_le_0ac474_idx'),
        ),
    ]
