# Generated by Django 6.0.5 on 2026-05-22 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('archivee', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_bailleur', to=settings.AUTH_USER_MODEL)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_locataire', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='logements.logement')),
            ],
            options={
                'verbose_name': 'Conversation',
                'ordering': ['-modifie_le'],
                'unique_together': {('locataire', 'bailleur', 'logement')},
            },
        ),
        migrations.CreateModel(
            name='ConversationChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_convs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Chatbot',
                'ordering': ['-modifie_le'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('non_lu', models.BooleanField(default=True)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('supprime', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MessageChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant IA')], max_length=10)),
                ('contenu', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversationchatbot')),
                ('logements_sugeres', models.ManyToManyField(blank=True, to='logements.logement')),
            ],
            options={
                'verbose_name': 'Message Chatbot',
                'ordering': ['cree_le'],
            },
        ),
    ]
