# Generated by Django 6.0.5 on 2026-05-21 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/')),
                ('ville', models.CharField(blank=True, default='Yaoundé', max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('LOCATAIRE', 'Locataire'), ('BAILLEUR', 'Bailleur'), ('ADMIN', 'Administrateur'), ('SUPER_ADMIN', 'Super Administrateur')], default='LOCATAIRE', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verify_token', models.CharField(blank=True, max_length=64)),
                ('reset_password_token', models.CharField(blank=True, max_length=64)),
                ('reset_password_expires', models.DateTimeField(blank=True, null=True)),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_push', models.BooleanField(default=True)),
                ('mode_sombre', models.BooleanField(default=False)),
                ('premium_debut', models.DateTimeField(blank=True, null=True)),
                ('premium_fin', models.DateTimeField(blank=True, null=True)),
                ('nb_connexions', models.PositiveIntegerField(default=0)),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('INSCRIPTION', 'Inscription'), ('MODIF_PROFIL', 'Modification profil'), ('MODIF_MDP', 'Changement mot de passe'), ('RESET_MDP', 'Réinitialisation MDP'), ('ANNONCE_CREATE', 'Création annonce'), ('ANNONCE_UPDATE', 'Modification annonce'), ('ANNONCE_DELETE', 'Suppression annonce'), ('RESERVATION', 'Réservation'), ('PAIEMENT', 'Paiement'), ('SIGNALEMENT', 'Signalement')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('succes', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'ordering': ['-cree_le'],
            },
        ),
    ]
